name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linting
      run: npm run lint
    
    - name: Run unit tests
      run: npm run test:unit
    
    - name: Run E2E tests
      run: npm run test:e2e
    
    - name: Generate test report
      run: |
        echo "# Test Run Report $(date +%Y-%m-%d)" > reports/testrun_$(date +%Y-%m-%d).md
        echo "## Summary" >> reports/testrun_$(date +%Y-%m-%d).md
        echo "- Unit Tests: $(npm run test:unit -- --json | jq '.numPassedTests') passed" >> reports/testrun_$(date +%Y-%m-%d).md
        echo "- E2E Tests: $(npm run test:e2e -- --json | jq '.numPassedTests') passed" >> reports/testrun_$(date +%Y-%m-%d).md
    
    - name: Upload test artifacts
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: |
          reports/
          coverage/
        if-no-files-found: error 